// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClientWinFormsExamples.ch05.Models;

public partial class JBXX
{
    public string XueHao { get; set; }

    public string XingMing { get; set; }

    public string XingBie { get; set; }

    public DateTime ChuShengRiQi { get; set; }

    public byte[] ZhaoPian { get; set; }
}