// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClientWinFormsExamples.ch05.Models;

public partial class KCBM
{
    public string Id { get; set; }

    public string KCMingCheng { get; set; }

    public string KCLeiBie { get; set; }
}