// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClientWinFormsExamples.ch05.Models;

public partial class KCCJ
{
    public int AutoID { get; set; }

    public string XueHao { get; set; }

    public string KCId { get; set; }

    public string XueNianXueQi { get; set; }

    public int ChengJi { get; set; }
}