// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Configuration;
using Microsoft.EntityFrameworkCore;

namespace ClientWinFormsExamples.ch05.Models;

public partial class MyDb1Context : DbContext
{
    public MyDb1Context()
    {
    }

    public MyDb1Context(DbContextOptions<MyDb1Context> options)
        : base(options)
    {
    }

    public virtual DbSet<JBXX> JBXX { get; set; }

    public virtual DbSet<KCBM> KCBM { get; set; }

    public virtual DbSet<KCCJ> KCCJ { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings["MyDb1"].ConnectionString);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<JBXX>(entity =>
        {
            entity.HasKey(e => e.XueHao).HasName("PK__JBXX__4C529802AB9F30AF");

            entity.Property(e => e.XueHao)
                .HasMaxLength(8)
                .IsFixedLength();
            entity.Property(e => e.ChuShengRiQi).HasColumnType("date");
            entity.Property(e => e.XingBie)
                .IsRequired()
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.XingMing)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<KCBM>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__KCBM__3214EC07D442615C");

            entity.Property(e => e.Id)
                .HasMaxLength(3)
                .IsFixedLength();
            entity.Property(e => e.KCLeiBie)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.KCMingCheng)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<KCCJ>(entity =>
        {
            entity.HasKey(e => e.AutoID).HasName("PK__KCCJ__6B23296587577EAD");

            entity.Property(e => e.KCId)
                .IsRequired()
                .HasMaxLength(3)
                .IsFixedLength();
            entity.Property(e => e.XueHao)
                .IsRequired()
                .HasMaxLength(8)
                .IsFixedLength();
            entity.Property(e => e.XueNianXueQi)
                .IsRequired()
                .HasMaxLength(11)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}