// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _2210050000_name_lab04.Models;

public partial class Student
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Age { get; set; }

    public double Grade { get; set; }
}