// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using _2210050000_name_lab04;
using Microsoft.EntityFrameworkCore;
namespace _2210050000_name_lab04.Models;

public partial class StudentDbContext : DbContext
{
    public StudentDbContext()
    {
    }

    public StudentDbContext(DbContextOptions<StudentDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Student> Student { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //=> optionsBuilder.UseSqlServer(@"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\2210050000_name_StudentTable.mdf;Integrated Security=True");
    => optionsBuilder.UseSqlServer(DataBaseConfig.ConnectionString); // 使用 DatabaseConfig.ConnectionString
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Student__3214EC074F66D686");
            /*
             * 如果不注释这行代码会报错
             Cannot insert explicit value for identity column in table 'Student' when IDENTITY_INSERT is set to OFF.
            这行代码告诉 Entity Framework (EF) Id 属性的值 永远不会 由数据库生成。 
            EF 认为您会在代码中手动设置 Id 的值，而不是让数据库的自增长功能来生成。
            在数据库中将 Id 列定义为 IDENTITY 列 (自增长)，数据库本身会负责为新插入的记录自动生成唯一的 Id 值。 
            但是.ValueGeneratedNever() 的配置 与数据库的自增长行为冲突了。
             */
            //entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}