//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataExampleWpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CJ
    {
        public int Id { get; set; }
        public string Xuehao { get; set; }
        public string KechengBianma { get; set; }
        public string Xueqi { get; set; }
        public string Xiuduleibie { get; set; }
        public Nullable<int> Chengji { get; set; }
        public string Beizhu { get; set; }
    }
}
